services:
  be:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: michaeltio/invoice-be-mdi
    ports:
      - "5000:5000"
    environment:
      APP_PORT: 5000
      DATABASE_URL: "postgresql://postgres:root@db:5432/invosync_db?schema=public"
      NODE_ENV: development
      JWT_SECRET_ACCESS: "exlaq3Q2gsWb74s4gkpGRUnH9pDIFGqo"
      JWT_SECRET_REFRESH: "pHjDg120skgOx3wG8GO02udxYFhZic1X"
      JWT_SECRET_ACCESS_LIFETIME: "15m"
      JWT_SECRET_REFRESH_LIFETIME: "30d"
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
    command: bash -c "bun run migrate && bunx prisma migrate deploy && bun run migrate:reset && bun seed && bun run start"

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: invosync_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - db_data:/var/lib/postgresql/data

  fe:
    # build:
    #   context: ../Invoice-web-app-react-main
    #   dockerfile: Dockerfile
    image: michaeltio/invoice-fe-mdi:latest
    ports:
      - "80:4173"
    # environment:
    #   VITE_API_URL: http://20.92.226.61:5000
    depends_on:
      - be

volumes:
  db_data:
